#ifndef SCREENSTATE_HPP_INCLUDED
#define SCREENSTATE_HPP_INCLUDED

enum ScreenState {
    TITLE_SCREEN,
    GAME_SCREEN_1,
    GAME_SCREEN_2,
    GAME_OVER_1,
    GAME_OVER_2,
    EXIT_GAME
};

#endif
